# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    # - name: Install swiftenv
    #   run: brew install kylef/formulae/swiftenv

    - name: Install Swift 6
      run: |
          brew update
          brew install swift

    # - name: Use Swift 6
    #   run: swiftenv global 6.0

    # - name: Verify Swift version
    #   run: swift --version

    - name: Resolve Dependencies
      run: swift package resolve
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
